variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  vmImageName: 'windows-latest'

stages:
- stage: pipeline
  displayName: CloudFlare.Client
  jobs: 
    - job: pipeline
      displayName: CI/CD Pipeline
      pool:
        vmImage: $(vmImageName)
      
      steps:
    
      - task: SonarCloudPrepare@1
        displayName: Prepare Sonar Cloud
        inputs:
          SonarCloud: 'SonarCloud'
          organization: 'zingz0r-github'
          scannerMode: 'MSBuild'
          projectKey: 'CloudFlare.Client'
          projectName: 'CloudFlare.Client'
          projectVersion: '$(Build.BuildNumber)'
          extraProperties: |
            sonar.exclusions=**/obj/**,**/*.dll,**/*Test.csproj,**/*Tests.cs
            sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/**/coverage.opencover.xml
            sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/*.trx
      
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
          feedsToUse: 'select'
          vstsFeed: 'd5f72524-9a3d-4cca-ac65-8688b67830d4/f7ea4fd7-43dc-4f24-a491-8f013b20ab55'
      
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: build
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration)'
      
      - task: DotNetCoreCLI@2
        displayName: 'Test'
        env:
          ApiKey: $(ApiKey)
          EmailAddress: $(EmailAddress)
        inputs:
          command: test
          projects: '**/*Test.csproj'
          arguments: '--no-build --configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat="cobertura%2copencover" /p:CoverletOutput=$(Build.SourcesDirectory)\TestResults\Coverage\'
          publishTestResults: true

      - task: SonarCloudAnalyze@1
        displayName: "Analyze Code with SonarCloud"

      - task: SonarCloudPublish@1
        displayName: "Publish Code Analysis Results to SonarCloud"
      
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish Code Coverage Report'
        inputs:
          codeCoverageTool: 'cobertura'
          summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'

      - task: DotNetCoreCLI@2
        displayName: 'Pack Release'
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
        inputs:
          command: pack
          packagesToPack: 'CloudFlare.Client/CloudFlare.Client.csproj'
          packDirectory: '$(Build.ArtifactStagingDirectory)/packages'
          arguments: '--no-build  --configuration $(buildConfiguration)'
          versioningScheme: 'byEnvVar'
          versionEnvVar: Build.SourceBranchName
          verbosityPack: Diagnostic

      - task: CopyFiles@2
        displayName: Copy Files
        inputs:
          SourceFolder: 'CloudFlare.Client/bin'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      
      - task: PublishBuildArtifacts@1
        displayName: Publish To Artifactory
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'

      - task: NuGetCommand@2
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
        displayName: 'Deploy Release to nuget.org'
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/packages/*.nupkg'
          nuGetFeedType: 'external'
          publishFeedCredentials: 'nuget.org'
          verbosityPush: Detailed

