variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  vmImageName: 'windows-latest'

stages:
- stage: buildandtest
  displayName: Build and Test
  jobs: 
    - job: buildandtest
      displayName: Build and Test
      pool:
        vmImage: $(vmImageName)
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
          feedsToUse: 'select'
          vstsFeed: 'd5f72524-9a3d-4cca-ac65-8688b67830d4/f7ea4fd7-43dc-4f24-a491-8f013b20ab55'
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: build
          projects: 'CloudFlare.Client/CloudFlare.Client.csproj'
          arguments: '--framework:netcoreapp3.1 --configuration $(buildConfiguration)'
      - task: DotNetCoreCLI@2
        displayName: 'Test'
        env:
          ApiKey: $(ApiKey)
          EmailAddress: $(EmailAddress)
        inputs:
          command: test
          projects: 'CloudFlare.Client.Test/CloudFlare.Client.Test.csproj'
          arguments: '--logger trx --framework:netcoreapp3.1 --configuration $(buildConfiguration) --collect "Code coverage"'
      - task: CopyFiles@2
        displayName: Copy Files
        inputs:
          SourceFolder: '${System.Default.WorkingDirectory}/CloudFlare.Client/bin'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        displayName: Publish To Artifactory
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'